$ErrorActionPreference = "Stop"

python train_rcadnet.py `
  --data-root data\pcm_restoration_train `
  --scenario motion_horizontal_medium `
  --scenario defocus_medium `
  --scenario lowlight_medium `
  --epochs 6 `
  --batch-size 1 `
  --patch-size 128 `
  --lr 3e-7 `
  --width 40 `
  --device cuda `
  --out runs\rmrnet_v24_detector_safe_pcm `
  --num-workers 0 `
  --code-source metadata_fused `
  --block-type evidence `
  --attention-type task `
  --conditioning gated_basis `
  --metadata-dropout 0.10 `
  --metadata-noise 0.01 `
  --edge-weight 0.15 `
  --freq-weight 0.05 `
  --defect-weight 0.10 `
  --visibility-weight 0.08 `
  --use-task-losses `
  --lambda-tdp 0.0015 `
  --lambda-jacobian 0.00002 `
  --lambda-active-contour 0.005 `
  --lambda-detector-input-anchor 0.0005 `
  --lambda-evidence-nonregression 0.02 `
  --evidence-lower-fraction 0.55 `
  --task-loss-warmup-epochs 6 `
  --tdp-yolo-weights runs\detect\runs\detect_train\yolov8n_pcm_clean_25ep\weights\best.pt `
  --tdp-layers 2,4 `
  --tdp-layer-weights 0.5,1.0 `
  --detector-input-size 320 `
  --jacobian-probes 1 `
  --cqmix-grid 4 `
  --debug-first-batches 0 `
  --init-weights runs\rmrnet_revised_evidence_30ep\rcadnet_best.pth `
  --val-data-root data\pcm_restoration_test `
  --val-scenario motion_horizontal_medium `
  --val-scenario defocus_medium `
  --val-scenario lowlight_medium `
  --val-every 1 `
  --save-every-epoch

